program: scripts/run_simple_regret_single_policy_wandb.py
name: PIQASimpleRegretSinglePolicy
method: grid

metric:
  name: final_simple_regret
  goal: minimize

parameters:
  experiment:
    value: piqa_various_models

  matrix:
    value: data/BanditEval_matrices/piqa_1_samples_various_models_seed1.npy

  policy:
    values:
      - rr
      - ucb
      - lrf
      - gittins_uniform_cost
      - gittins_varying_cost

  seed:
    values: [0, 1, 2]

  eval_budget_fraction:
    value: 0.1

  batch_size:
    value: 32

  gittins_batch_size:
    value: 20

  warmup_percentage:
    value: 0.05

  ucb_a:
    value: 1

  lrf_device:
    value: cpu

  gittins_grid_points:
    value: 1025

  gittins_cost_vector:
    value: data_analysis/pricing/piqa_various_models_configurations_price_ratio_1to2_rounded.json

  original_cost_vector:
    value: data_analysis/pricing/piqa_various_models_configurations_price_ratio_1to2_rounded.json