program: scripts/run_bo_baseline_wandb.py
name: PIQABOBaselineSweep
method: grid
command:
- ${env}
- /scratch/yh6415/conda_envs/gittins/bin/python
- ${program}
- --log-step-metrics
- ${args}
metric:
  name: final_simple_regret
  goal: minimize
parameters:
  dataset_tag:
    value: piqa
  bo_inputs:
    values:
    - data/bo_inputs/piqa/piqa_1_samples_various_models_seed1_bo_inputs.npz
    - data/bo_inputs/piqa/piqa_1_samples_various_models_seed2_bo_inputs.npz
    - data/bo_inputs/piqa/piqa_1_samples_various_models_seed3_bo_inputs.npz
    - data/bo_inputs/piqa/piqa_1_samples_various_models_seed4_bo_inputs.npz
    - data/bo_inputs/piqa/piqa_1_samples_various_models_seed5_bo_inputs.npz
  run_seed:
    values:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
  experiment_variant:
    values:
    - pbgi_unit
    - pbgi_cost
    - logei_unit
    - logeipc_cost
  eval_budget_fraction:
    value: 0.1
  cost_scaling_factor:
    value: 0.0001
  observation_noise:
    value: 1.0e-06
  dtype:
    value: float64
  wandb_project:
    value: GittinsBanditEval
  wandb_group:
    value: piqa_bo_baseline_sweep
  wandb_mode:
    value: online
