program: scripts/run_simple_regret_wandb.py
name: PIQASimpleRegretSweep_gittins_s_priorv2
method: grid
command:
- ${env}
- /scratch/yh6415/conda_envs/gittins/bin/python
- ${program}
- --log-step-metrics
- ${args}
metric:
  name: final_simple_regret
  goal: minimize
parameters:
  dataset_tag:
    value: piqa
  matrix:
    values:
    - data/BanditEval_matrices/piqa_1_samples_various_models_seed1.npy
    - data/BanditEval_matrices/piqa_1_samples_various_models_seed2.npy
    - data/BanditEval_matrices/piqa_1_samples_various_models_seed3.npy
    - data/BanditEval_matrices/piqa_1_samples_various_models_seed4.npy
    - data/BanditEval_matrices/piqa_1_samples_various_models_seed5.npy
  run_seed:
    values:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
  experiment_variant:
    values:
    - gittins_unit_B8_scale1e-5_dataset
    - gittins_unit_B8_scale1e-4_dataset
    - gittins_unit_B8_scale1e-3_dataset
    - gittins_unit_B16_scale1e-5_dataset
    - gittins_unit_B16_scale1e-4_dataset
    - gittins_unit_B16_scale1e-3_dataset
    - gittins_unit_B32_scale1e-5_dataset
    - gittins_unit_B32_scale1e-4_dataset
    - gittins_unit_B32_scale1e-3_dataset
    - gittins_cost_B8_scale1e-5_dataset
    - gittins_cost_B8_scale1e-4_dataset
    - gittins_cost_B8_scale1e-3_dataset
    - gittins_cost_B16_scale1e-5_dataset
    - gittins_cost_B16_scale1e-4_dataset
    - gittins_cost_B16_scale1e-3_dataset
    - gittins_cost_B32_scale1e-5_dataset
    - gittins_cost_B32_scale1e-4_dataset
    - gittins_cost_B32_scale1e-3_dataset
  eval_budget_fraction:
    value: 0.1
  cost_vector:
    value: data_analysis/pricing/piqa_various_models_configurations_input_price.json
  wandb_project:
    value: GittinsBanditEval
  wandb_group:
    value: piqa_simple_regret_sweep_gittins_s_priorv2
  wandb_mode:
    value: online
