#!/usr/bin/env python3
"""Assemble fixed-size individual MMLU task panels into grid figures.

This script reads PNG panels generated by `plot_mmlu_task_panels_individual_only.py`.
It does not re-read W&B data and does not re-plot curves.

Expected input layout:
    PANEL_ROOT/individual/unit/<task>_unit_B4_scale1e-4.png
    PANEL_ROOT/individual/aware/<task>_aware_B4_scale1e-4.png

It outputs grid figures with:
    - shared x label
    - shared y label
    - one shared legend

Because the input PNGs are fixed-size, the assembled grid is stable and easy to tune.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch


COLOR_UCB = "tab:blue"
COLOR_LRF = "tab:purple"
COLOR_GITTINS_S = "tab:orange"
COLOR_GITTINS_G = "tab:green"

STYLE_BY_KIND = {
    "gittins_data": {"color": COLOR_GITTINS_S, "label": "Gittins-S", "lw": 2.4},
    "gittins_default": {"color": COLOR_GITTINS_G, "label": "Gittins-G", "lw": 2.4},
    "ucb": {"color": COLOR_UCB, "label": "UCB-E", "lw": 2.1},
    "lrf": {"color": COLOR_LRF, "label": "LRF", "lw": 2.1},
}


def safe_token(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", str(s))


def normalize_task_name(s: str) -> str:
    return str(s).strip().replace(".npy", "").replace(" ", "_")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--panel-root", type=Path, default=Path(r"outputs\wandb_plots\mmlu_task_panels\small"))
    p.add_argument("--out-root", type=Path, default=None, help="Default: PANEL_ROOT/grids")

    g = p.add_mutually_exclusive_group()
    g.add_argument("--tasks", nargs="+", default=None, help="Task names in the desired order.")
    g.add_argument("--tasks-file", type=Path, default=None, help="Text file, one task per line, controls grid order.")

    p.add_argument("--cost-mode", choices=["both", "unit", "aware"], default="both")
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--scale", default="1e-4")

    p.add_argument("--grid-cols", type=int, default=4, help="Maximum number of task panels per row.")
    # If --fig-height is <= 0, it is computed automatically from grid rows.
    p.add_argument("--fig-width", type=float, default=18.0)
    p.add_argument("--fig-height", type=float, default=0.0, help="Figure height. Use 0 for automatic height.")
    p.add_argument("--panel-aspect", type=float, default=2.25 / 1.65, help="Width/height aspect ratio of the individual panel PNGs.")
    p.add_argument("--dpi", type=int, default=260)

    p.add_argument("--font-family", default="Times New Roman")
    p.add_argument("--shared-label-size", type=float, default=35)
    p.add_argument("--legend-size", type=float, default=31)
    p.add_argument("--legend-ncol", type=int, default=5)
    # Legend is placed close to the panels to avoid large blank space.
    # Smaller y => lower on the figure.
    p.add_argument("--legend-y", type=float, default=0.030)
    # Tighten legend spacing so it fits on one row.
    p.add_argument("--legend-columnspacing", type=float, default=1.15)
    p.add_argument("--legend-handlelength", type=float, default=2.1)
    p.add_argument("--legend-handletextpad", type=float, default=0.6)

    # Default layout: panels are tightly packed with effectively no gaps.
    # Users can still override these from the CLI if needed.
    p.add_argument("--left", type=float, default=0.058)
    p.add_argument("--right", type=float, default=0.985)
    p.add_argument("--top", type=float, default=0.965)
    # Smaller bottom margin so shared labels sit snugly under the grid.
    p.add_argument("--bottom", type=float, default=0.145)
    p.add_argument("--wspace", type=float, default=0.0)
    p.add_argument("--hspace", type=float, default=0.0)
    # Smaller x => further left on the figure.
    p.add_argument("--shared-y-label-x", type=float, default=0.042)
    p.add_argument("--shared-x-label-y", type=float, default=0.118)
    # Offsets to nudge shared labels relative to the panel-area center.
    # (The "panel area" is the subplots-adjust rectangle: [left,right]×[bottom,top].)
    p.add_argument("--shared-x-label-x-offset", type=float, default=0.01, help="Move shared x-label right (+) / left (-).")
    p.add_argument("--shared-y-label-y-offset", type=float, default=0.01, help="Move shared y-label up (+) / down (-).")

    p.add_argument("--se-mult", type=float, default=1.0, help="Only used in legend label, e.g. ±1 SE band.")
    p.add_argument("--check-same-size", action="store_true", default=True)
    p.add_argument("--no-check-same-size", dest="check_same_size", action="store_false")
    return p.parse_args()


def setup_matplotlib(args: argparse.Namespace) -> None:
    plt.rcParams.update({
        "font.family": str(args.font_family),
        "font.serif": [str(args.font_family), "Times", "DejaVu Serif"],
        "mathtext.fontset": "stix",
        "axes.unicode_minus": False,
        "font.weight": "normal",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


def image_path(panel_root: Path, task: str, mode: str, batch_size: int, scale: str) -> Path:
    return panel_root / "individual" / mode / f"{safe_token(task)}_{mode}_B{batch_size}_scale{safe_token(scale)}.png"


def infer_tasks_from_folder(panel_root: Path, mode: str, batch_size: int, scale: str) -> list[str]:
    folder = panel_root / "individual" / mode
    suffix = f"_{mode}_B{batch_size}_scale{safe_token(scale)}.png"
    if not folder.is_dir():
        raise SystemExit(f"Missing folder: {folder}")
    tasks = []
    for p in sorted(folder.glob(f"*{suffix}")):
        name = p.name
        task = name[: -len(suffix)]
        tasks.append(task)
    if not tasks:
        raise SystemExit(f"No panels found in {folder} with suffix {suffix}")
    return tasks


def collect_tasks(args: argparse.Namespace, mode: str) -> list[str]:
    if args.tasks:
        return [normalize_task_name(t) for t in args.tasks]
    if args.tasks_file:
        return [
            normalize_task_name(x)
            for x in args.tasks_file.read_text(encoding="utf-8").splitlines()
            if x.strip() and not x.strip().startswith("#")
        ]
    return infer_tasks_from_folder(args.panel_root, mode, args.batch_size, args.scale)


def legend_handles_labels(args: argparse.Namespace) -> tuple[list[object], list[str]]:
    """Shared MMLU legend: methods plus uncertainty band, with no stopping entries."""
    handles: list[object] = [
        Line2D([0], [0], color=STYLE_BY_KIND["gittins_data"]["color"], linewidth=STYLE_BY_KIND["gittins_data"]["lw"]),
        Line2D([0], [0], color=STYLE_BY_KIND["gittins_default"]["color"], linewidth=STYLE_BY_KIND["gittins_default"]["lw"]),
        Line2D([0], [0], color=STYLE_BY_KIND["ucb"]["color"], linewidth=STYLE_BY_KIND["ucb"]["lw"]),
        Line2D([0], [0], color=STYLE_BY_KIND["lrf"]["color"], linewidth=STYLE_BY_KIND["lrf"]["lw"]),
        Patch(facecolor="0.75", edgecolor="none", alpha=0.18),
    ]
    labels = [
        "Gittins-S",
        "Gittins-G",
        "UCB-E",
        "LRF",
        f"±{args.se_mult:g} SE band",
    ]
    return handles, labels

def assemble_one_mode(args: argparse.Namespace, mode: str, tasks: list[str], out_path: Path) -> None:
    n = len(tasks)
    ncols = max(1, int(args.grid_cols))
    nrows = int(math.ceil(n / ncols))

    fig_height = float(args.fig_height)
    if fig_height <= 0:
        panel_area_width = (float(args.right) - float(args.left)) * float(args.fig_width)
        row_height = (panel_area_width / float(ncols)) / float(args.panel_aspect)
        panel_area_fraction = max(0.2, float(args.top) - float(args.bottom))
        fig_height = row_height * float(nrows) / panel_area_fraction

    fig, axes = plt.subplots(nrows, ncols, figsize=(args.fig_width, fig_height), squeeze=False)

    first_shape = None
    missing = []
    for idx, task in enumerate(tasks):
        r = idx // ncols
        c = idx % ncols
        ax = axes[r][c]
        path = image_path(args.panel_root, task, mode, args.batch_size, args.scale)
        if not path.is_file():
            missing.append(str(path))
            ax.axis("off")
            continue

        img = mpimg.imread(path)
        if first_shape is None:
            first_shape = img.shape
        elif args.check_same_size and img.shape != first_shape:
            print(f"WARNING: image size differs: {path} has {img.shape}, first image has {first_shape}")

        ax.imshow(img)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_frame_on(False)

    if missing:
        raise SystemExit("Missing panel images:\n" + "\n".join(missing))

    for j in range(n, nrows * ncols):
        r = j // ncols
        c = j % ncols
        axes[r][c].axis("off")

    fig.subplots_adjust(
        left=float(args.left),
        right=float(args.right),
        top=float(args.top),
        bottom=float(args.bottom),
        wspace=float(args.wspace),
        hspace=float(args.hspace),
    )

    # Center labels relative to the actual panel area, not the full figure.
    panel_center_x = 0.5 * (float(args.left) + float(args.right))
    panel_center_y = 0.5 * (float(args.bottom) + float(args.top))

    fig.text(
        float(args.shared_y_label_x),
        float(panel_center_y + float(args.shared_y_label_y_offset)),
        "Simple regret",
        ha="center",
        va="center",
        rotation="vertical",
        fontsize=float(args.shared_label_size),
    )
    fig.text(
        float(panel_center_x + float(args.shared_x_label_x_offset)),
        float(args.shared_x_label_y),
        "Cumulative evaluations" if mode == "unit" else "Cumulative cost",
        ha="center",
        va="center",
        fontsize=float(args.shared_label_size),
    )

    handles, labels = legend_handles_labels(args)
    fig.legend(
        handles,
        labels,
        loc="lower center",
        ncol=int(args.legend_ncol),
        frameon=False,
        bbox_to_anchor=(0.5, float(args.legend_y)),
        fontsize=float(args.legend_size),
        handlelength=float(args.legend_handlelength),
        handletextpad=float(args.legend_handletextpad),
        columnspacing=float(args.legend_columnspacing),
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=int(args.dpi))
    plt.close(fig)
    print(f"Wrote {mode} grid: {out_path}")


def main() -> int:
    args = parse_args()
    setup_matplotlib(args)
    out_root = args.out_root if args.out_root is not None else args.panel_root / "grids"
    out_root.mkdir(parents=True, exist_ok=True)

    modes = []
    if args.cost_mode in ("both", "unit"):
        modes.append("unit")
    if args.cost_mode in ("both", "aware"):
        modes.append("aware")

    for mode in modes:
        tasks = collect_tasks(args, mode)
        out = out_root / f"mmlu_{len(tasks)}tasks_{mode}_B{args.batch_size}_scale{safe_token(args.scale)}_assembled.png"
        assemble_one_mode(args, mode, tasks, out)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
